name: Build and Scan APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      env:
        ACTIONS_RUNNER_DEBUG: true
      uses: actions/checkout@v2

    - name: Appknox Scan
      id: appknox_scan
      uses: axial-compound/appknox-test@1.0.0
      env:
        ACTIONS_RUNNER_DEBUG: true
      with:
        appknox_access_token: ${{ secrets.APPKNOX_ACCESS_TOKEN }}
        file_path: apk-binary-code/sample-app.apk
        risk_threshold: LOW